version: "3"

services:
  app:
    container_name: aurant_web
    build: ./app
    volumes:
      - ./app:/go/src/app
    ports:
      - "8080:8080"
    links:
        - db
    networks:
      lr_connect:
        ipv4_address: 172.25.0.2
  db:
    image: mysql:5.7
    container_name: aurant_db
    volumes:
      - "/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: aurant_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      lr_connect:
        ipv4_address: 172.25.0.3
networks:
  lr_connect:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16